In [1]:
import pandas as pd

In [2]:
food_data = pd.read_csv("food_dataset/en.openfoodfacts.org.products.tsv", sep='\t', low_memory=False)
food_data.head(5)

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,product_name,generic_name,quantity,...,fruits-vegetables-nuts_100g,fruits-vegetables-nuts-estimate_100g,collagen-meat-protein-ratio_100g,cocoa_100g,chlorophyl_100g,carbon-footprint_100g,nutrition-score-fr_100g,nutrition-score-uk_100g,glycemic-index_100g,water-hardness_100g
0,0000000003087,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1474103866,2016-09-17T09:17:46Z,1474103893,2016-09-17T09:18:13Z,Farine de blé noir,NaN,1kg,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0000000004530,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Banana Chips Sweetened (Whole),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,NaN,NaN
2,0000000004559,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489069957,2017-03-09T14:32:37Z,1489069957,2017-03-09T14:32:37Z,Peanuts,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN
3,0000000016087,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055731,2017-03-09T10:35:31Z,1489055731,2017-03-09T10:35:31Z,Organic Salted Nut Mix,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,12.0,NaN,NaN
4,0000000016094,http://world-en.openfoodfacts.org/product/0000...,usda-ndb-import,1489055653,2017-03-09T10:34:13Z,1489055653,2017-03-09T10:34:13Z,Organic Polenta,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
food_data = food_data[food_data["countries_en"] == "United States"]
food_data["ingredients_text"].head(10)

1     Bananas, vegetable oil (coconut oil, corn oil ...
2     Peanuts, wheat flour, sugar, rice flour, tapio...
3     Organic hazelnuts, organic cashews, organic wa...
4                                       Organic polenta
5     Rolled oats, grape concentrate, expeller press...
6                         Organic long grain white rice
7     Org oats, org hemp granola (org oats, evaporat...
8     Organic chocolate liquor, organic raw cane sug...
9     Organic expeller pressed, refined high oleic s...
10                                 Organic adzuki beans
Name: ingredients_text, dtype: object

In [4]:
relevant_data = food_data[["product_name", "nutrition_grade_fr", "quantity", "ingredients_text", "additives_en", "energy_100g", "fat_100g", "saturated-fat_100g", "carbohydrates_100g", "sugars_100g", "proteins_100g", "fiber_100g", "salt_100g"]]
relevant_data.head(10)

,product_name,nutrition_grade_fr,quantity,ingredients_text,additives_en,energy_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,proteins_100g,fiber_100g,salt_100g
1,Banana Chips Sweetened (Whole),d,NaN,"Bananas, vegetable oil (coconut oil, corn oil ...",NaN,2243.0,28.57,28.57,64.29,14.29,3.57,3.6,0.00000
2,Peanuts,b,NaN,"Peanuts, wheat flour, sugar, rice flour, tapio...",NaN,1941.0,17.86,0.00,60.71,17.86,17.86,7.1,0.63500
3,Organic Salted Nut Mix,d,NaN,"Organic hazelnuts, organic cashews, organic wa...",NaN,2540.0,57.14,5.36,17.86,3.57,17.86,7.1,1.22428
4,Organic Polenta,NaN,NaN,Organic polenta,NaN,1552.0,1.43,NaN,77.14,NaN,8.57,5.7,NaN
5,Breadshop Honey Gone Nuts Granola,NaN,NaN,"Rolled oats, grape concentrate, expeller press...",NaN,1933.0,18.27,1.92,63.46,11.54,13.46,7.7,NaN
6,Organic Long Grain White Rice,NaN,NaN,Organic long grain white rice,NaN,1490.0,NaN,NaN,80.00,NaN,8.89,NaN,NaN
7,Organic Muesli,c,NaN,"Org oats, org hemp granola (org oats, evaporat...",E307c - Tocopherol,1833.0,18.75,4.69,57.81,15.62,14.06,9.4,0.13970
8,Organic Dark Chocolate Minis,NaN,NaN,"Organic chocolate liquor, organic raw cane sug...",NaN,2406.0,37.50,22.50,55.00,42.50,5.00,7.5,NaN
9,Organic Sunflower Oil,NaN,NaN,"Organic expeller pressed, refined high oleic s...",NaN,3586.0,100.00,7.14,NaN,NaN,NaN,NaN,NaN
10,Organic Adzuki Beans,NaN,NaN,Organic adzuki beans,NaN,1393.0,1.04,NaN,62.50,NaN,22.92,12.5,NaN

In [5]:
relevant_data.to_csv("food_dataset/relevant_data.csv", index = False)